#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const store = require('./store');

function generateBrain(projectRoot) {
  if (!projectRoot || typeof projectRoot !== 'string') {
    throw new Error('A valid project root path is required.');
  }
  const config = store.loadConfig(projectRoot);
  const maxLines = config.brain_max_lines || 180;
  const priorityOrder = config.priority_order || ['conventions', 'decisions', 'lessons', 'knowledge'];

  const lines = [];
  lines.push('# Team Brain');
  lines.push('');
  lines.push('> Auto-generated from .team-brain/ entries. Do not edit manually.');
  lines.push('> Regenerate with: /team-brain sync');
  lines.push('');

  for (const type of priorityOrder) {
    const entries = store.listEntries(projectRoot, type).filter(e => e.meta.status !== 'deprecated');
    if (entries.length === 0) continue;

    // Check if we have room
    if (lines.length >= maxLines - 5) break;

    const sectionTitle = type.charAt(0).toUpperCase() + type.slice(1);
    lines.push(`## ${sectionTitle}`);
    lines.push('');

    const maxPerSection = config.max_entries_per_section || 20;
    const shown = entries.slice(0, maxPerSection);

    for (const entry of shown) {
      if (lines.length >= maxLines - 2) break;

      const title = entry.meta.title || entry.filename;
      const author = config.include_authors ? ` (${entry.meta.author || 'unknown'})` : '';
      const date = config.include_dates ? ` [${entry.meta.date || ''}]` : '';

      if (type === 'conventions') {
        // Conventions get the full first paragraph
        const firstPara = entry.body.trim().split('\n\n')[0].replace(/^#+\s.*\n?/, '').trim();
        lines.push(`- **${title}**: ${firstPara}`);
      } else if (type === 'decisions') {
        const status = entry.meta.status || 'accepted';
        lines.push(`- **${title}** (${status})${date}${author}`);
      } else {
        lines.push(`- ${title}${date}${author}`);
      }
    }

    if (entries.length > maxPerSection) {
      lines.push(`- _...and ${entries.length - maxPerSection} more_`);
    }
    lines.push('');
  }

  // Stats footer
  const allEntries = store.listEntries(projectRoot);
  const contributors = store.getContributors(projectRoot);
  lines.push('---');
  lines.push(`_${allEntries.length} entries by ${Object.keys(contributors).length} contributors. Last updated: ${store.today()}_`);

  const content = lines.slice(0, maxLines).join('\n') + '\n';
  const brainPath = path.join(store.brainDir(projectRoot), 'BRAIN.md');
  fs.writeFileSync(brainPath, content);

  return { path: brainPath, lines: lines.length, truncated: lines.length > maxLines };
}

function injectIntoClaude(projectRoot) {
  if (!projectRoot || typeof projectRoot !== 'string') {
    throw new Error('A valid project root path is required.');
  }
  const claudePath = path.join(projectRoot, 'CLAUDE.md');
  const brainPath = path.join(store.brainDir(projectRoot), 'BRAIN.md');

  if (!fs.existsSync(brainPath)) generateBrain(projectRoot);
  const brainContent = fs.readFileSync(brainPath, 'utf8');

  const startMarker = '<!-- team-brain:start -->';
  const endMarker = '<!-- team-brain:end -->';
  const injection = `${startMarker}\n${brainContent}\n${endMarker}`;

  if (fs.existsSync(claudePath)) {
    let claude = fs.readFileSync(claudePath, 'utf8');
    const regex = new RegExp(`${startMarker}[\\s\\S]*?${endMarker}`, 'g');
    if (regex.test(claude)) {
      claude = claude.replace(regex, injection);
    } else {
      claude = claude.trimEnd() + '\n\n' + injection + '\n';
    }
    fs.writeFileSync(claudePath, claude);
  } else {
    fs.writeFileSync(claudePath, injection + '\n');
  }

  return { path: claudePath };
}

function generateCursorrules(projectRoot) {
  const conventions = store.listEntries(projectRoot, 'conventions').filter(e => e.meta.status !== 'deprecated');
  const decisions = store.listEntries(projectRoot, 'decisions').filter(e => e.meta.status === 'accepted');

  const lines = [];
  lines.push('# Project Rules (auto-generated by Team Brain)');
  lines.push('');

  if (conventions.length > 0) {
    lines.push('## Conventions');
    lines.push('');
    for (const c of conventions) {
      const firstPara = c.body.trim().split('\n\n')[0].replace(/^#+\s.*\n?/, '').trim();
      lines.push(`- ${c.meta.title}: ${firstPara}`);
    }
    lines.push('');
  }

  if (decisions.length > 0) {
    lines.push('## Architecture Decisions');
    lines.push('');
    for (const d of decisions) {
      lines.push(`- ${d.meta.title}`);
    }
    lines.push('');
  }

  const rulesPath = path.join(projectRoot, '.cursorrules');
  fs.writeFileSync(rulesPath, lines.join('\n'));
  return { path: rulesPath };
}

function generateAgentsMd(projectRoot) {
  const conventions = store.listEntries(projectRoot, 'conventions').filter(e => e.meta.status !== 'deprecated');
  const decisions = store.listEntries(projectRoot, 'decisions').filter(e => e.meta.status === 'accepted');
  const knowledge = store.listEntries(projectRoot, 'knowledge').filter(e => e.meta.status !== 'deprecated');

  const lines = [];
  lines.push('# AGENTS.md');
  lines.push('');
  lines.push('> Auto-generated by Team Brain. Do not edit manually.');
  lines.push('');

  if (conventions.length > 0) {
    lines.push('## Coding Conventions');
    lines.push('');
    for (const c of conventions) {
      const firstPara = c.body.trim().split('\n\n')[0].replace(/^#+\s.*\n?/, '').trim();
      lines.push(`- **${c.meta.title}**: ${firstPara}`);
    }
    lines.push('');
  }

  if (decisions.length > 0) {
    lines.push('## Architecture Decisions');
    lines.push('');
    for (const d of decisions) {
      lines.push(`- **${d.meta.title}** (${d.meta.status}) — ${d.meta.date}`);
    }
    lines.push('');
  }

  if (knowledge.length > 0) {
    lines.push('## Project Knowledge');
    lines.push('');
    for (const k of knowledge) {
      lines.push(`- ${k.meta.title}`);
    }
    lines.push('');
  }

  const agentsPath = path.join(projectRoot, 'AGENTS.md');
  fs.writeFileSync(agentsPath, lines.join('\n'));
  return { path: agentsPath };
}

module.exports = { generateBrain, injectIntoClaude, generateCursorrules, generateAgentsMd };

if (require.main === module) {
  const [,, cmd, ...args] = process.argv;
  const root = args[0] || store.findProjectRoot();

  switch (cmd) {
    case 'generate':
    case 'brain':
      const result = generateBrain(root);
      console.log(`BRAIN.md generated (${result.lines} lines${result.truncated ? ', truncated' : ''})`);
      break;
    case 'inject':
      const inj = injectIntoClaude(root);
      console.log(`Injected into ${inj.path}`);
      break;
    case 'cursorrules':
      const cr = generateCursorrules(root);
      console.log(`Generated ${cr.path}`);
      break;
    case 'agents':
      const ag = generateAgentsMd(root);
      console.log(`Generated ${ag.path}`);
      break;
    default:
      console.log('Commands: generate [root], inject [root], cursorrules [root], agents [root]');
  }
}
